# 公共配置，所有的服务都共同拥有的参数
logging:
  level:
    org.springframework.security: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

# 配置OAuth2  SSO地址
security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current

spring:
  rabbitmq:
    host: rabbitmq